### ISSUE TITLE
File sent to server is empty

### ISSUE THREAD

**Issue by AdelMimoun** [Nexific/dart_ftpclient#15]
When trying to send a file to an FTP server, the received file is 0 bytes, also when sending files to the company server filenames get jumbled except for the first charchter.

**To Reproduce**
I tested this on a public FTP server (https://dlptest.com/ftp-test/) as well as my company's server, both in ascii and binary mode, with the following code:
```
 Future<String> sendFileTest(File file) async {
    //TODO:remove this method
    String status = "failure";
    final FTPClient ftp =
        FTPClient("ftp.dlptest.com",
            user: "dlpuser@dlptest.com",
            pass: "SzMf7rTE4pCrf9dV286GuNe4N",
            debug: true,
            timeout: 10);
    try {
      ftp.connect();
    } catch (e) {
      print(e);
      return status;
    }
    try {
      ftp.uploadFile(file, mode: TransferMode.binary);
      status = "success";
    } catch (e) {
      print(e);
      return status;
    } finally {
      ftp.disconnect();
    }
    return status;
  }
```

**Screenshots**
files when sent to the public server, notice they are 0 bytes
![sent-to-public-server](https://user-images.githubusercontent.com/57043552/80597566-4f2e9800-8a28-11ea-801e-255ad5825c22.PNG)

files when sent to the company server, filename is wrong except for the first letter
![sent-to-company-server](https://user-images.githubusercontent.com/57043552/80598613-ea743d00-8a29-11ea-8afe-e6344709da52.PNG)

**Platform:**
 - Flutter
 

**Smartphone (when using Flutter):**
 - Devices: Huawei p20 pro CLT L29[Android 9], 
                 Android Emulator[Android 6]

**Log**

```
I/flutter ( 3692): [29.04.2020 14:55:54.548] Connecting...
I/flutter ( 3692): [29.04.2020 14:55:54.753] < 220 (vsFTPd 2.0.5)
I/flutter ( 3692): [29.04.2020 14:55:54.754] > USER usr_ftp
I/flutter ( 3692): [29.04.2020 14:55:54.857] < 331 Please specify the password.
I/flutter ( 3692): [29.04.2020 14:55:54.857] > PASS ftp_usr
I/flutter ( 3692): [29.04.2020 14:55:54.960] < 230 Login successful.
I/flutter ( 3692): [29.04.2020 14:55:54.960] Connected!
I/flutter ( 3692): [29.04.2020 14:55:54.960] > CWD /colombus/timeless/exprecup/inventar
I/flutter ( 3692): [29.04.2020 14:55:55.063] < 250 Directory successfully changed.
I/flutter ( 3692): [29.04.2020 14:55:55.064] Upload File: /data/user/0/com.frista.inventoryscanner/app_flutter/awaitingFolder/8J88_29-04-2020_14:51:43.PAQ
I/flutter ( 3692): [29.04.2020 14:55:55.065] > TYPE I
I/flutter ( 3692): [29.04.2020 14:55:55.169] < 200 Switching to Binary mode.
I/flutter ( 3692): [29.04.2020 14:55:55.169] > PASV
I/flutter ( 3692): [29.04.2020 14:55:55.272] < 227 Entering Passive Mode (10,101,0,1,227,240)
I/flutter ( 3692): [29.04.2020 14:55:55.272] > STOR 8J88_29-04-2020_14:51:43.PAQ
I/flutter ( 3692): [29.04.2020 14:55:55.273] Opening DataSocket to Port 58352
I/flutter ( 3692): [29.04.2020 14:55:55.273] Disconnecting...
I/flutter ( 3692): [29.04.2020 14:55:55.273] > QUIT
I/flutter ( 3692): [29.04.2020 14:55:55.274] Disconnected!
E/flutter ( 3692): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: type 'OSError' is not a subtype of type 'int'
E/flutter ( 3692): #0      _NativeSynchronousSocket.available (dart:io-patch/sync_socket_patch.dart:122:24)
E/flutter ( 3692): #1      _RawSynchronousSocket.available (dart:io-patch/sync_socket_patch.dart:33:30)
E/flutter ( 3692): #2      FTPSocket.readResponse (package:ftpclient/src/ftpsocket.dart:33:25)
E/flutter ( 3692): #3      FileUpload.uploadFile (package:ftpclient/src/commands/fileupload.dart:48:36)
E/flutter ( 3692): <asynchronous suspension>
E/flutter ( 3692): #4      FTPClient.uploadFile (package:ftpclient/src/ftpclient_base.dart:58:43)
E/flutter ( 3692): #5      FTPManager.sendFileTest (package:inventoryscanner/Logic/FTPManager.dart:31:11)
E/flutter ( 3692): #6      _FileCardState.build.<anonymous closure> (package:inventoryscanner/Elements/FileCard.dart:88:24)
E/flutter ( 3692): <asynchronous suspension>
E/flutter ( 3692): #7      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter ( 3692): #8      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter ( 3692): #9      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter ( 3692): #10     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter ( 3692): #11     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter ( 3692): #12     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:236:7)
E/flutter ( 3692): #13     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter ( 3692): #14     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:222:20)
E/flutter ( 3692): #15     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter ( 3692): #16     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter ( 3692): #17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter ( 3692): #18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter ( 3692): #19     _rootRunUnary (dart:async/zone.dart:1138:13)
E/flutter ( 3692): #20     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 3692): #21     _CustomZone.runUnaryGuarded (dart:async/zone.dart:933:7)
E/flutter ( 3692): #22     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter ( 3692): #23     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter ( 3692): 
```

**Comment by virtualmarc** [comment]
Have you tried the latest published version on pub dev with the async upload? 

It it's already the newest version your example won't work, since uploadFile is async. You have to use await in your example (or subscribe the future).

**Comment by AdelMimoun** [comment]
The solution you suggested fixed te empty file issue, thanks 👍. The jumbled filename issue remains, but after some investigation I found that it may be caused by the server not reading correctly UTF-8 filenames (https://www.synology.com/en-global/knowledgebase/DSM/tutorial/File_Sharing/Why_do_I_see_unreadable_filenames_after_uploading_the_files_via_FTP).  I guess this issue can be closed.
